### ISSUE TITLE
Support of netcoreapp1.1 or netstandart1.6

### ISSUE THREAD

**Issue by ibobkovitransition** [poulfoged/Elasticsearch-Inside#12]
It's impossible to add "elasticsearch-inside" throw nuget.
As I can see it supports net461 only.

So, are you going to add support of netcoreapp1.0+ or netstandart1.3+?

**Comment by poulfoged** [comment]
Happy to accept a MR ...

**Comment by o-mdr** [comment]
A related PR is now available https://github.com/poulfoged/Elasticsearch-Inside/pull/23. It should be easy to add `netcoreapp1.0` or similar
