### ISSUE TITLE
Add support for .NET Standard 2.0

### ISSUE THREAD

**Issue by bravecobra** [poulfoged/Elasticsearch-Inside#14]
Migrating to .NET Standard 2.0 should be fairly simple. That should keep net461 supported at the same time.

**Comment by umerfaruk** [comment]
Is there any plan to start work on dotnet core?

**Comment by umerfaruk** [comment]
Doesn't seems like a simple port. The project has a dependency on LZ4PCL which only support full framework.

**Comment by bravecobra** [comment]
Sure, but lz4net has support for .netstandard 1.0. There is no need to stick to the lz4pcl library as I don't expect any updates on that one. Pcl is basically dead with the arrival of .netstandard. Switching to lz4net, should make it work while keeping the same functionality. I could try cooking up a pull request, if you want to.

**Comment by bravecobra** [comment]
The relevant repo is [MiloszKrajewski/lz4net](https://github.com/MiloszKrajewski/lz4net). According to the readme, it supports all (most?) .NET platforms: .NET 2.0+, .NET 4.0+, .NET Core, Mono, Windows Phone, Xamarin.iOS, Xamarin.Android and Silverlight.

**Comment by poulfoged** [comment]
Yes, lz4net looks like a good drop-in replacement

**Comment by rmadisonhaynie** [comment]
@bravecobra are you working on the PR?

**Comment by bravecobra** [comment]
@rmadisonhaynie no, not at the moment, but I don't expect it to be too hard.
This code only zips and unzips without any fancy specs as far as I can see. So the required calls should stay fairly simple as well. Then, once replaced, upgrading to a .netstandard version should be fairly straightforward.

**Comment by o-mdr** [comment]
This is now addressed in a PR https://github.com/poulfoged/Elasticsearch-Inside/pull/23
