### ISSUE TITLE
Elastic-Version Update

### ISSUE THREAD

**Issue by SimonJonasGubler** [poulfoged/Elasticsearch-Inside#15]
Hi Poul

Are there future plans to update Elasticsearch-Inside to newer versions of Elastic? Our company is using ElasticSearch 5.5 and we are running integration tests with Elasticsearch-Inside which runs on ElasticSearch 5.3. When version 6 is out we would like to upgrade sooner or later but we don't know if Elasticsearch-Inside will be updated to the new version then.

If there are no plans to upgrade Elasticsearch-Inside we have to consider changing the testing framework so that we can rely on our integration tests.

Kind regards 
Simon

**Comment by poulfoged** [comment]
Hi Simon,

I'll look into it and get back to you.

Lately I've been considering a different setup for my own tests - running against a single instance but with a layer in between to isolate tests.

**Comment by poulfoged** [comment]
6.x is out now :)

https://www.nuget.org/packages/elasticsearch-inside/6.0.0
