### ISSUE TITLE
Update Elasticsearch version

### ISSUE THREAD

**Issue by Jasper136** [poulfoged/Elasticsearch-Inside#18]
Hello Poul

I forked your repo to update the version of Elasticsearch in Elasticsearch-Inside, because I am trying to use and test some of the features of Elasticsearch that are introduced in later versions than 6.0.0.
Git is preventing me from pushing all the changes (to create a pull request) because the size of the Elasticsearch executable now exceeds 100MB. The solution would be to use [Git LFS](https://git-lfs.github.com/), but there is [a limitation on public forks](https://help.github.com/articles/collaboration-with-git-large-file-storage/#pushing-large-files-to-forks).
Is it possible for you to enable the use of Git LFS, update the version of Elasticsearch yourself or make me a collaborator to the repo? It would be great to keep this awesome library up-to-date with the latest version of Elasticsearch!

Kind regards
Jasper

**Comment by poulfoged** [comment]
Hi,

Sry for the late response. You should have an invite

**Comment by Jasper136** [comment]
All right,thanks a lot!
I created PR19. I also added the possibility to add files to the config folder.
Please review, PR should be able to merge automatically.
