### ISSUE TITLE
Unexpected high memory usage (5.0.0-alpha5)

### ISSUE THREAD

**Issue by kendaleiv** [poulfoged/Elasticsearch-Inside#6]
It doesn't look like **5.0.0-alpha5** is using the defaults defined in https://github.com/poulfoged/Elasticsearch-Inside/blob/26ac73f56060ae62918c1278622d2bab484e457c/source/ElasticsearchInside/CommandLine/ElasticsearchParameters.cs#L23-L27 for memory usage. Processes appear to use significantly more memory.

**Comment by poulfoged** [comment]
Yes, I see it. Thanks I'll investigate....

**Comment by poulfoged** [comment]
Ok, I've lowered the defaults from 2g to 128m.

The configuration is has actually changed compared to the one you link to. All JVM settings can now be changed via .JVMParameters in the configuration and defaults are read from jvm.options (official file from Elasticsearch)

**Comment by kendaleiv** [comment]
Great, thanks! I'll let it up to you if you want to close this issue (depending if you like to wait for next package version before closing or not).

**Comment by poulfoged** [comment]
The change is in v5.0.0 that I released yesterday - including nuget.
